### ISSUE TITLE
self autocomplete

### ISSUE THREAD

**Issue by aallnneess** [mikatuo/vscode-defold-buddy#1]
Hey :-)

Will there ever be a "self" autocomplete on variables added in other functions ?

thanks 
matze

**Comment by mikatuo** [comment]
Hey
Here is how I did it:

```lua
go.property("jump_speed", 360)
go.property("gravity", 550)

function init(self) --[[@param self PlayerData]]
	self.hello = 5
end

function update(self, dt) --[[@param self PlayerData]] --[[@param dt number]]
end

---@class PlayerData
---@field jump_speed number
---@field gravity number
---@field hello number
```

![image](https://user-images.githubusercontent.com/7230306/234058399-ed0c422f-c968-4e81-b0aa-f067e238ca74.png)

**Comment by mikatuo** [comment]
In the extension v0.9.8 when a script file is generated with "Create Game Object" menu option:

<img width="277" alt="Screen Shot 2023-08-28 at 10 54 10 PM" src="https://github.com/mikatuo/vscode-defold-buddy/assets/7230306/ff567bff-4e07-4c11-a90d-dc20820badf6">

The generated script file will have all parameters annotated. The rest is up to you to add fields (see examples at the top) to the generated type and you will have autocompletion. This is the most I can do for you. Hope it helps.

![2023-08-28_22-50](https://github.com/mikatuo/vscode-defold-buddy/assets/7230306/d676fd0d-d14c-4eb0-86a5-61ba2be7306c)
