### ISSUE TITLE
[Create files from Explorer context menu] Pressing ESC doesn't abort creation of files.

### ISSUE THREAD

**Issue by hristo-kanchev** [mikatuo/vscode-defold-buddy#2]
# Description:
ESC doesn't seem to abort creation of files.

Issue is present for both Game Object, Gui, Lua module.
<img width="357" alt="image" src="https://github.com/mikatuo/vscode-defold-buddy/assets/23095052/144f7dfd-0547-41eb-bdb8-d5cd6c6c1936">

## System:
OS: WIndows 11
VSCode Version: 1.82.2

## Repro steps:

Create a new Game Object via Explorer:
<img width="431" alt="image" src="https://github.com/mikatuo/vscode-defold-buddy/assets/23095052/7c974cf0-a21b-4c84-9016-058f0ca5df0b">

Popup appears to create the Game Object:
<img width="665" alt="image" src="https://github.com/mikatuo/vscode-defold-buddy/assets/23095052/801ead65-9438-448d-b726-4a53f077c75d">

**Press ESC** popup proceeds with creation of Game Object and displays options:
<img width="664" alt="image" src="https://github.com/mikatuo/vscode-defold-buddy/assets/23095052/0d8ec07c-b80f-42fd-b5ec-3a02d9d91405">

**Press ESC** popup closes and empty game object called "player.go" is created.
<img width="289" alt="image" src="https://github.com/mikatuo/vscode-defold-buddy/assets/23095052/ce095cee-b5e4-4dbd-980e-130027539cf7">

**Comment by mikatuo** [comment]
Thanks for reporting! Annoying bugs. Fixed https://github.com/mikatuo/vscode-defold-buddy/commit/2e170fd7c646463f370166a92f9c5b3063a3bd22

**Comment by hristo-kanchev** [comment]
Thanks @mikatuo! <3
