### ISSUE TITLE
Add hot-reload trigger on saving a gui_script

### ISSUE THREAD

**Issue by redoak** [mikatuo/vscode-defold-buddy#5]
I noticed that a hot-reload is not triggered by saving a gui_script. But once modified, they will be hot-reloaded if a script is saved.

**Comment by mikatuo** [comment]
Fixed in v1.3.7 https://github.com/mikatuo/vscode-defold-buddy/commit/9d969629289b4cd241fecb63cf5bddbe0bf42fa3
