### ISSUE TITLE
Feature request: Add hot reload support for transpiled languages

### ISSUE THREAD

**Issue by thinknathan** [mikatuo/vscode-defold-buddy#6]
At [ts-defold](https://github.com/ts-defold), we run the TypescriptToLua transpiler to convert Typescript to Lua. Since we use `.ts` files, they don't trigger hot reload in Defold Buddy.

I was able to add support in a fairly naive way: add '.ts' as a file extension that triggers hot reload, and add a slight delay to give the transpiler time to finish before calling the hot reload. [View commit](https://github.com/thinknathan/vscode-defold-buddy/commit/146207c0c637d492ff2208c8a52efc30a69b4da9). This isn't the most elegant solution, but it works for me.

I understand this may be outside the scope of this extension, but I thought I'd start the discussion.

**Comment by mikatuo** [comment]
I would be glad to help add support for it. I tried `ts-defold` a while ago and can't remember how it worked. If it compiles to .lua files then in theory VS Code should detect that .lua files changed so it's a bit strange that it doesn't work.

**Comment by mikatuo** [comment]
Fixed in v1.4.0.

![Screen Recording 2024-05-20 at 6 01 38 PM](https://github.com/mikatuo/vscode-defold-buddy/assets/7230306/599eaea4-11e9-4e65-9b7e-16ab99238edb)

**Comment by thinknathan** [comment]
Works great. Thank you!
