### ISSUE TITLE
game.project dependencies in .defold/assets/** folder persist upon removal 

### ISSUE THREAD

**Issue by ig-gh** [mikatuo/vscode-defold-buddy#7]
Thank you for this wonderful vscode plugin @mikatuo.

Adding a new project dependency will add it to assets dir.
Removal of the dependency will leave its files, both if we run `fetch buddy ` command or  delete `.defold` folder and run `index` and `fetch` commands.

Due to caching, fetching will not "work" until `?timestamp` is added to dependency url
_edit:_
or by disabling an extension and re-enabling it again (.defold/assets/[dir] will appear) 

![defold_dependency](https://github.com/mikatuo/vscode-defold-buddy/assets/3739505/b2610ab0-3982-42b0-a24c-a5bf472fbeae)
![ghost_library](https://github.com/mikatuo/vscode-defold-buddy/assets/3739505/cc057c5b-3a9d-451d-abd8-1df7a5fe048d)

Q:
Maybe during `buddy init` all cache should be cleared and `buddy fetch` will force get the libraries?

**Comment by mikatuo** [comment]
The buddy fetch command is the same as clicking "Fetch libraries" in Defold editor. The described caching is coming from the Defold editor. Defold stores fetched dependencies in the `.internal/lib` folder.

<img width="265" alt="image" src="https://github.com/mikatuo/vscode-defold-buddy/assets/7230306/745e3fac-ed05-4dc9-9c57-4bf21d6f46f0">

I think that "Re-fetch libraries" command could be useful for someone. Maybe there is already a feature request in Defold Github repo - something worth checking if you are interested.
Meanwhile, it could be added to the Buddy extension as a new command that clears the `.internal/lib` folder automatically. A PR would be welcome :)
